#!/bin/bash

##############################################################################
# OpenClaw Secure VM - Initial Setup & System Hardening Script
# Purpose: Prepare VMware VM with security best practices
# Runs on: Ubuntu 22.04+ or CentOS 8+
# Usage: sudo ./01-initial-setup.sh
##############################################################################

set -euo pipefail

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging variables
LOG_DIR="/var/log/openclaw-setup"
LOG_FILE="${LOG_DIR}/initial-setup-$(date +%Y%m%d-%H%M%S).log"

# Create log directory
mkdir -p "$LOG_DIR"

# Logging function
log() {
    local level=$1
    shift
    local message="$@"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo -e "${timestamp} [${level}] ${message}" | tee -a "$LOG_FILE"
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log "ERROR" "This script must be run as root"
        exit 1
    fi
}

# Detect OS
detect_os() {
    if [[ -f /etc/os-release ]]; then
        . /etc/os-release
        OS=$ID
        OS_VERSION=$VERSION_ID
    else
        log "ERROR" "Cannot detect OS"
        exit 1
    fi
    log "INFO" "Detected OS: ${OS} ${OS_VERSION}"
}

# Update system packages
update_system() {
    log "INFO" "Updating system packages..."
    
    if [[ "$OS" == "ubuntu" ]]; then
        apt-get update -qq
        DEBIAN_FRONTEND=noninteractive apt-get upgrade -y -qq
        apt-get install -y -qq \
            curl wget git unzip vim nano \
            net-tools htop tmux \
            build-essential \
            openssh-server openssh-client \
            sudo fail2ban \
            apparmor apparmor-utils \
            ufw
    elif [[ "$OS" == "centos" ]] || [[ "$OS" == "rhel" ]]; then
        yum update -y -q
        yum install -y -q \
            curl wget git unzip vim nano \
            net-tools htop tmux \
            gcc make \
            openssh-server openssh-clients \
            sudo fail2ban \
            selinux-policy selinux-policy-devel \
            firewalld
    fi
    
    log "INFO" "System packages updated successfully"
}

# Configure SSH security
configure_ssh() {
    log "INFO" "Hardening SSH configuration..."
    
    SSH_CONFIG="/etc/ssh/sshd_config"
    SSH_CONFIG_D="/etc/ssh/sshd_config.d/99-hardened.conf"
    
    # Create backup
    cp "$SSH_CONFIG" "${SSH_CONFIG}.backup.$(date +%Y%m%d)"
    
    # Create hardened SSH config file
    cat > "$SSH_CONFIG_D" << 'EOF'
# Hardened OpenSSH Configuration
# Generated by OpenClaw Secure Setup

# Network and Protocol
Port 22
Protocol 2
AddressFamily any
ListenAddress 0.0.0.0
ListenAddress ::

# Authentication - Disable weak methods
PermitRootLogin no
PermitEmptyPasswords no
PasswordAuthentication no
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys .ssh/authorized_keys2

# Change authentication grace time
LoginGraceTime 30s
MaxAuthTries 3
MaxSessions 10

# Security
StrictModes yes
IgnoreRhosts yes
HostbasedAuthentication no
RhostsRSAAuthentication no
RSAAuthentication no

# Logging
SyslogFacility AUTH
LogLevel VERBOSE

# Timeouts
ClientAliveInterval 300
ClientAliveCountMax 2

# Ciphers and Keying Exchange (Modern Security)
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com

# Other security options
X11Forwarding no
PrintMotd yes
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server

# Banner
Banner /etc/issue.net
EOF
    
    # Validate SSH config
    if ! sshd -t; then
        log "ERROR" "SSH configuration is invalid"
        cp "${SSH_CONFIG}.backup.$(date +%Y%m%d)" "$SSH_CONFIG"
        exit 1
    fi
    
    systemctl restart ssh || systemctl restart sshd
    log "INFO" "SSH hardening completed"
}

# Configure Firewall
configure_firewall() {
    log "INFO" "Configuring firewall..."
    
    if [[ "$OS" == "ubuntu" ]]; then
        # UFW setup
        ufw --force enable
        ufw default deny incoming
        ufw default allow outgoing
        
        # Allow SSH (critical!)
        ufw allow 22/tcp
        # Allow Tailscale
        ufw allow 41641/udp
        
        log "INFO" "UFW firewall enabled"
    elif [[ "$OS" == "centos" ]] || [[ "$OS" == "rhel" ]]; then
        # FirewallD setup
        systemctl enable firewalld
        systemctl start firewalld
        
        firewall-cmd --permanent --set-default-zone=public
        firewall-cmd --permanent --add-port=22/tcp
        firewall-cmd --permanent --add-port=41641/udp
        firewall-cmd --reload
        
        log "INFO" "FirewallD configured"
    fi
}

# Setup Fail2Ban
setup_fail2ban() {
    log "INFO" "Setting up Fail2Ban for brute-force protection..."
    
    cat > /etc/fail2ban/jail.local << 'EOF'
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 3
destemail = root@localhost

[sshd]
enabled = true
port = ssh
logpath = /var/log/auth.log
backend = systemd
EOF
    
    systemctl enable fail2ban
    systemctl restart fail2ban
    log "INFO" "Fail2Ban configured and started"
}

# Configure automatic security updates
setup_auto_updates() {
    log "INFO" "Configuring automatic security updates..."
    
    if [[ "$OS" == "ubuntu" ]]; then
        apt-get install -y -qq unattended-upgrades apt-listchanges
        dpkg-reconfigure -plow unattended-upgrades
        
        cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}";
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};
Unattended-Upgrade::Mail "root";
Unattended-Upgrade::MailReport "on-change";
Unattended-Upgrade::AutoFixInterruptedDpkg true;
Unattended-Upgrade::MinimalSteps true;
EOF
        
    elif [[ "$OS" == "centos" ]] || [[ "$OS" == "rhel" ]]; then
        yum install -y -q yum-cron
        systemctl enable yum-cron
        systemctl start yum-cron
    fi
    
    log "INFO" "Automatic security updates enabled"
}

# Configure kernel hardening
configure_kernel_hardening() {
    log "INFO" "Applying kernel hardening parameters..."
    
    cat >> /etc/sysctl.conf << 'EOF'

# Kernel Hardening
kernel.kptr_restrict = 2
kernel.dmesg_restrict = 1
kernel.printk = 3 3 3 3
kernel.unprivileged_bpf_disabled = 1
kernel.unprivileged_userns_clone = 0
kernel.yama.ptrace_scope = 3

# Network Hardening
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.ip_forward = 0
net.ipv6.conf.all.forwarding = 0
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0

# SYN Flood Protection
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 4096

# ICMP Protection
net.ipv4.icmp_ignore_bogus_error_responses = 1

# TCP Hardening
net.ipv4.tcp_timestamps = 0
EOF
    
    sysctl -p > /dev/null
    log "INFO" "Kernel hardening applied"
}

# Setup fail2ban monitoring
setup_monitoring() {
    log "INFO" "Setting up basic monitoring..."
    
    # Create monitoring script
    mkdir -p /usr/local/bin
    cat > /usr/local/bin/check-system-health.sh << 'EOF'
#!/bin/bash
# System health check script

echo "=== System Health Check ==="
echo "CPU Usage:"
top -bn1 | head -n3 | tail -n2
echo ""
echo "Memory Usage:"
free -h
echo ""
echo "Disk Usage:"
df -h /
echo ""
echo "Load Average:"
uptime
echo ""
echo "Failed SSH Attempts (last 24h):"
grep "Failed password" /var/log/auth.log 2>/dev/null | tail -5 || echo "None"
echo ""
echo "Recent Service Errors:"
journalctl -p err -n 5
EOF
    
    chmod +x /usr/local/bin/check-system-health.sh
    
    # Create cron job for daily health check (2 AM)
    echo "0 2 * * * /usr/local/bin/check-system-health.sh | mail -s 'System Health Report' root" | \
    crontab -
    
    log "INFO" "Monitoring setup completed"
}

# Configure SELinux (CentOS/RHEL)
configure_selinux() {
    if [[ "$OS" == "centos" ]] || [[ "$OS" == "rhel" ]]; then
        log "INFO" "Configuring SELinux..."
        
        semanage login -m -S targeted -s sysadm_u -r s0-s0:c0.c1023 __default__
        setenforce 1
        
        log "INFO" "SELinux configured to enforcing mode"
    fi
}

# Create system audit rules
setup_audit() {
    log "INFO" "Setting up audit rules..."
    
    if [[ "$OS" == "ubuntu" ]]; then
        apt-get install -y -qq auditd audispd-plugins
    elif [[ "$OS" == "centos" ]] || [[ "$OS" == "rhel" ]]; then
        yum install -y -q audit audit-libs
    fi
    
    cat >> /etc/audit/rules.d/openclaw.rules << 'EOF'
# Monitor system calls
-a always,exit -F arch=b64 -S adjtimex,settimeofday -k time-change
-a always,exit -F arch=b32 -S adjtimex,settimeofday,stime -k time-change
-a always,exit -F arch=b64 -S clock_settime -k time-change
-a always,exit -F arch=b32 -S clock_settime -k time-change
-w /etc/localtime -p wa -k time-change

# Monitor user/group changes
-w /etc/group -p wa -k identity
-w /etc/passwd -p wa -k identity
-w /etc/shadow -p wa -k identity

# Monitor network modifications
-a always,exit -F arch=b64 -S sethostname,setdomainname -k network-modifications
EOF
    
    systemctl enable auditd
    systemctl restart auditd
    
    log "INFO" "Audit rules configured"
}

# Summary report
print_summary() {
    cat << 'EOF'

╔════════════════════════════════════════════════════════════════╗
║        Initial Setup & Hardening - COMPLETED ✓                ║
╚════════════════════════════════════════════════════════════════╝

✓ System packages updated
✓ SSH hardened (key-based auth only)
✓ Firewall configured (UFW/FirewallD)
✓ Fail2Ban installed for brute-force protection
✓ Automatic security updates enabled
✓ Kernel hardening parameters applied
✓ System monitoring configured
✓ Audit rules configured

NEXT STEPS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Ensure SSH keys are properly configured
2. Test SSH connection with key-based authentication
3. Disconnect all password-based connections
4. Run: sudo ./02-install-openclaw.sh

IMPORTANT SECURITY REMINDERS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚠  SSH password authentication is DISABLED
⚠  Only SSH keys will work from this point
⚠  Add your public key to ~/.ssh/authorized_keys
⚠  Keep your SSH private key SECURE

Logs saved to: $LOG_FILE

EOF
}

# Error handler
error_handler() {
    local line_number=$1
    log "ERROR" "Script failed at line $line_number"
    exit 1
}

trap 'error_handler ${LINENO}' ERR

# Main execution
main() {
    log "INFO" "Starting OpenClaw Secure VM - Initial Setup"
    log "INFO" "User: $(whoami)"
    log "INFO" "Hostname: $(hostname)"
    
    check_root
    detect_os
    update_system
    configure_ssh
    configure_firewall
    setup_fail2ban
    setup_auto_updates
    configure_kernel_hardening
    setup_audit
    configure_selinux
    setup_monitoring
    
    log "INFO" "Initial setup completed successfully"
    print_summary
}

main "$@"
